### ISSUE TITLE
Support latest API version

### ISSUE THREAD

**Issue by hofbi** [voxel-dot-at/bta_tof_driver#2]
Currently the ros driver supports API version `v2.1`. Right now the latest available API version is `v2.2.6` which is not supported.

**Comment by ljburtz** [comment]
This issue can be closed. Since version 0.1.1 (2018-07-17) API version 2.5.2 is supported.
See [changelog](https://github.com/voxel-dot-at/bta_tof_driver/blob/master/CHANGELOG.rst)
