### ISSUE TITLE
Compatibility with DepthEye 3D Visual TOF Depth Camera

### ISSUE THREAD

**Issue by pfs-db** [voxel-dot-at/bta_tof_driver#4]
Do you think that is possible do use this driver to a camera that is in the link below
https://www.seeedstudio.com/DepthEye-3D-visual-TOF-Depth-Camera-p-3025.html

If not, do you know any driver from ROS that works on that camera?

**Comment by svogl** [comment]
Did not have my hands on this camera, but they're surely incompatible.
It should not be too hard to write an adapter layer for it, though if you use the bta driver as a template.
Simon
