### ISSUE TITLE
unable to change integration time and frame rate

### ISSUE THREAD

**Issue by Praveen290192** [voxel-dot-at/bta_tof_driver#7]
After running the roslaunch seeing an warning messages as error setting intergration time status as  -32767
and error setting frame rate : -32767

**Comment by angelmerino** [comment]
Hi,
can you tell me which camera are you using and your configuration. I guess, you are not getting a connection to the camera. This why those values are shown.

**Comment by Praveen290192** [comment]
Melexis EVK75123 and EVK75023

**Comment by angelmerino** [comment]
I would check the network configuration to be sure you are able to ping the camera. If you are using linux on a virtual machine, check also network and firewall configuration.

**Comment by Praveen290192** [comment]
I am connected to camera via ethernet on Jetson TX2
and I am able to change the reg values using rqt though.

#Parameter server configuration for bta_ros.
deviceType: 1

udpDataIpAddrLen: 4
udpDataIpAddr: {
n1: 224,
n2: 0,
n3: 0,
n4: 1,
}
udpDataPort: 10002

tcpDeviceIpAddrLen: 4
tcpDeviceIpAddr: {
n1: 192,
n2: 168,
n3: 0,
n4: 10,
}
tcpDeviceIpAddrLen: 4
tcpControlPort: 10001

#udpControlOutIpAddr: 
#udpControlOutIpAddrLen:
#udpControlPort:
#udpControlInIpAddr:
#udpControlInIpAddrLen:
#udpControlCallbackPort: 
#tcpDataPort:
#uartPortName:
#uartBaudRate:
#uartDataBits:
#uartStopBits:
#uartParity:
#uartTransmitterAddress:
#uartReceiverAddress
#serialNumber:
#calibFileName:

frameMode: 1
frameQueueMode: 1
verbosity: 5
frameQueueLength: 1

# Optional parameter.
#frameRate: 15
#integrationTime: 1500
```

**Comment by angelmerino** [comment]
Are you also able to read values from registers with rqt?
if so, you shouldn't see those errors after running roslaunch.

Configuration looks ok.
are you able to ping the camera?
If so at least tcp connection should work fine and roslaunch shouldn't give any error.
If no issues with firewall, upd should also work and you should be getting images.

**Comment by Praveen290192** [comment]
I am able to ping camera 
I am also getting images and point cloud from it but not able to re-config it. Will check with firewall.
And one more think how to make permanent changes in write reg value. When we power cycle camera it's getting default reg value

**Comment by angelmerino** [comment]
Ok fine.
Is reconfiguring not working or setting a different parameter in the config file?
Flashing the register content to persist them is not implemented in the ros driver.
Try with the manufacturer viewer on windows.
Still you can set the values you want in the config file and it should set them right after connecting to the camera. 
Of course only those parameter available in the "BltTofApi" (BTA_Config in bta.h)
