### ISSUE TITLE
ROS Noetic Support

### ISSUE THREAD

**Issue by DasSchilli** [voxel-dot-at/bta_tof_driver#9]
Hello,

I try to use the pkg, but I have some issues with the compilation:

Ubuntu 20.04
ROS Noetic

I follow your Setup and got following outputs:

![image](https://user-images.githubusercontent.com/71312359/196939724-2fac280e-74e5-438b-9737-4816ade25ddb.png)

**Comment by DasSchilli** [comment]
After uncomment these lines

https://github.com/voxel-dot-at/bta_tof_driver/blob/539e5259fb2b26f26fb21e987f9dc75b992e6fe2/src/bta_tof_driver.cpp#L416-L419

and installing two missing libraries 

```
sudo apt-get install libturbojpeg0-dev libturbojpeg
sudo apt-get install libusb-0.1-4
```

the compilation works.

**Comment by svogl** [comment]
thanks for pointing that out - I'll test with a VM and patch accordingly

**Comment by DasSchilli** [comment]
Some ideas for improvements:

- dynamic reconfigure extension for llPower, ModFreq, ImageProc and Flying Pixel etc. better usability as writing register
- support cad model as dae file, load as urdf file

**Comment by DasSchilli** [comment]
> thanks for pointing that out - I'll test with a VM and patch accordingly

Thank you!
